# Generated by Django 4.2.1 on 2023-05-31 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['name']},
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['name'], name='articles_ar_name_91dc70_idx'),
        ),
    ]
